### ISSUE TITLE
SMB Clients Added to image for External Storage SMB and CIFs Access 

### ISSUE THREAD

**Issue by tbarnes8** [klutchell/balena-nextcloud#2]
When Enabling and configuring the External Storage Module there is an error ""smbclient" is not installed. Mounting of "SMB / CIFS", "SMB / CIFS using OC login" is not possible. Please ask your system administrator to install it."

**Comment by klutchell** [comment]
If you're planning to use SMB/CIFS then `smbclient` can be added to the `app` Dockerfile. Otherwise that warning can be ignored. 

https://github.com/klutchell/balena-nextcloud/blob/ab6c075f6bd84a15778f73f4b6b06a43783ffdd2/app/Dockerfile#L4

If you think it's a common requirement feel free to open a PR and we can merge it for everyone!

**Comment by tbarnes8** [comment]
Thank you for the quick update, I am new to balena / docker and am still learning my way around. I think this would be good for all users. Where do I submit the PR? Thank you for the information.

**Comment by tbarnes8** [comment]
I see the PR, thanks.
